_target_: rectified_point_flow.encoder.PointCloudTeacher
encoder: null
embed_dim: 256
repr_dim: 1728      # output dimension of Concerto large
lmbda: 0.5
loss_type: cosine
head_type: edgeconv
num_neighbors: 5