# Feature extraction

defaults:
  - model: encoder/ptv3_object
  - data: ikea_partnet_everyday_twobytwo_modelnet_tudl_objverse
  - trainer: infer
  - visualizer: overlap
  - _self_

# Data
data_root: ./demo/data
data:
  dataset_names: []      # [] means using all datasets in the data_root
  batch_size: 1
  num_workers: 1

# Log directory
log_dir: ./demo/features

# Checkpoint path
ckpt_path: ./weights/RPF_base_pretrain_ep600.ckpt          # when null, the checkpoint will be downloaded from Hugging Face

# Model settings
model:
  compute_overlap_points: false
  build_overlap_head: false