_target_: rectified_point_flow.visualizer.OverlapVisualizationCallback


save_dir: ${log_dir}

# We support the following renderers:
# - "mitsuba": Use Mitsuba for high quality ray-traced rendering.
# - "pytorch3d": Use PyTorch3D's PointRasterizer for fast rendering.
# - "none": Do not save any visualizations.
renderer: pytorch3d

# Point cloud settings
center_points: false
scale_to_original_size: false

# Color settings
# "matplotlib:<name>": Use matplotlib colormap of the given name, e.g. "matplotlib:viridis"
colormap: matplotlib:Blues

# Image settings
image_size: 480           # Output resolution (square image)
point_radius: 0.015       # Radius of sphere of each point

# Camera parameters
camera_dist: 4.0          # Distance from the camera to the point cloud center
camera_elev: 30.0         # Elevation angle above the horizon
camera_azim: 45.0         # Azimuth angle on the horizon plane
camera_fov: 40.0          # Field of view